# Generated by Django 2.1.1 on 2018-10-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='loginpost',
            name='title',
            field=models.CharField(default='用户登录:', max_length=150),
        ),
        migrations.AlterField(
            model_name='loginpost',
            name='username',
            field=models.CharField(default='登录账号:', max_length=150),
        ),
        migrations.AlterField(
            model_name='loginpost',
            name='userpws',
            field=models.CharField(default='密码输入:', max_length=150),
        ),
    ]
